use std::path::{Path, PathBuf};

use onecoat::Error;
use onecoat::jsonc::{self, Edit, Splice};
use onecoat::model::theme::{Theme, Validated};
use onecoat::render::wt;
use onecoat::themes::ThemeSet;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("wt")
        .join(name)
}

fn text(name: &str) -> String {
    std::fs::read_to_string(fixture(name)).unwrap()
}

fn themes() -> ThemeSet {
    ThemeSet::load(Path::new("no-such-user-theme-directory")).unwrap()
}

fn nord(set: &ThemeSet) -> &Theme<Validated> {
    set.get("nord").unwrap()
}

fn splice_into(source: &str, edits: &[Edit]) -> Splice {
    jsonc::splice(&fixture("settings.json"), source, edits).unwrap()
}

fn settings_edits(set: &ThemeSet) -> Vec<Edit> {
    wt::settings_edits(nord(set)).unwrap()
}

fn fragment_edits(set: &ThemeSet) -> Vec<Edit> {
    wt::fragment_edits(nord(set)).unwrap()
}

#[test]
fn the_three_owned_keys_are_spliced_into_the_settings_file() {
    let set = themes();
    let spliced = splice_into(&text("settings.json"), &settings_edits(&set));

    assert_eq!(spliced.text, text("settings-spliced.json"));
    assert_eq!(
        spliced.changed,
        [
            jsonc::Key::parse("theme"),
            jsonc::Key::parse("themes"),
            jsonc::Key::parse("profiles.defaults.colorScheme"),
        ]
    );
}

#[test]
fn unrelated_text_survives_the_splice() {
    let set = themes();
    let spliced = splice_into(&text("settings.json"), &settings_edits(&set));

    for kept in [
        "// This file was initially generated by Windows Terminal 1.24.11911.0",
        "// To view the default settings, hold \"alt\" while clicking on the \"Settings\" button.",
        "    \"profiles\": \n",
        "            \"colorScheme\": \"One Half Dark\",",
        "            \"name\": \"One Half Dark\",",
        "            \"brightYellow\": \"#E5C07B\"",
    ] {
        assert!(
            spliced.text.contains(kept),
            "the splice dropped or rewrote {kept:?}"
        );
    }
    assert!(
        !spliced
            .text
            .contains("\"One Half Dark\",\n                \"light\""),
        "the splice must not repoint a profile pin"
    );
}

#[test]
fn the_other_side_of_a_pair_and_a_foreign_window_theme_survive() {
    let set = themes();
    let spliced = splice_into(&text("settings-crlf.json"), &settings_edits(&set));

    assert_eq!(spliced.text, text("settings-crlf-spliced.json"));
    assert!(
        spliced
            .text
            .contains("    \"theme\": {\r\n        \"light\": \"light\",\r\n        \"dark\": \"onecoat-dark\"\r\n    },\r\n"),
        "the light side keeps its own theme:\n{}",
        spliced.text
    );
    assert!(
        spliced
            .text
            .contains("        {\r\n            \"name\": \"mine\",\r\n            \"tabRow\": {\r\n                \"background\": \"#202020\"\r\n            }\r\n        },\r\n"),
        "the foreign window theme is kept byte for byte:\n{}",
        spliced.text
    );
    assert!(
        spliced
            .text
            .contains("\"colorScheme\": {\r\n                \"dark\": \"onecoat-dark\",\r\n                \"light\": \"Campbell\"\r\n            }"),
        "the previous scheme name carries into the light side:\n{}",
        spliced.text
    );
    assert_eq!(
        spliced.text.matches('\n').count(),
        spliced.text.matches("\r\n").count(),
        "every line ending keeps its carriage return"
    );
}

#[test]
fn a_second_splice_is_byte_identical() {
    let set = themes();
    let once = splice_into(&text("settings.json"), &settings_edits(&set));
    let twice = splice_into(&once.text, &settings_edits(&set));

    assert_eq!(twice.text, once.text);
    assert!(twice.changed.is_empty(), "{:?}", twice.changed);
}

#[test]
fn the_fragment_upsert_leaves_the_other_schemes_alone() {
    let set = themes();
    let source = text("previous-fragment.json").replace(
        "  \"schemes\": [\n",
        "  \"schemes\": [\n    {\n      \"name\": \"onecoat-light\",\n      \"background\": \"#eceff4\"\n    },\n",
    );
    let spliced = splice_into(&source, &fragment_edits(&set));

    assert!(
        spliced.text.contains(
            "    {\n      \"name\": \"onecoat-light\",\n      \"background\": \"#eceff4\"\n    },"
        ),
        "the other slot's scheme is kept byte for byte:\n{}",
        spliced.text
    );
    assert_eq!(
        spliced.changed,
        [jsonc::Key::parse("schemes")],
        "the upsert reports the array it owns"
    );
}

#[test]
fn the_fragment_is_created_from_an_empty_document() {
    let set = themes();
    let spliced = jsonc::splice(
        &fixture("schemes.json"),
        jsonc::NEW_DOCUMENT,
        &fragment_edits(&set),
    )
    .unwrap();

    assert_eq!(spliced.text, text("nord-dark-fragment.json"));
    assert_eq!(spliced.changed, [jsonc::Key::parse("schemes")]);
}

#[test]
fn a_broken_document_names_the_file_and_the_line() {
    let set = themes();
    let error = jsonc::splice(
        &fixture("settings-broken.json"),
        &text("settings-broken.json"),
        &settings_edits(&set),
    )
    .unwrap_err();

    assert!(
        matches!(
            &error,
            Error::JsoncUnparseable {
                line: 9,
                column: 1,
                ..
            }
        ),
        "{error}"
    );
    let message = error.to_string();
    assert!(message.contains("settings-broken.json"), "{message}");
    assert!(message.contains("line 9"), "{message}");
}

#[test]
fn a_key_of_the_wrong_type_is_never_clobbered() {
    let set = themes();
    let source = text("settings.json").replace("\"themes\": []", "\"themes\": {}");
    let error =
        jsonc::splice(&fixture("settings.json"), &source, &settings_edits(&set)).unwrap_err();

    assert!(
        matches!(&error, Error::KeyNotLocatable { key, expected, .. } if key.to_string() == "themes" && *expected == "a JSON array"),
        "{error}"
    );
}
